version: '3.8'

services:
  webserver:
    build: ./Web_server
    ports:
      - "8080:80"             # Expose the web server on host port 8080
    networks:
      - mon_reseau            # Connect to the specified network
    depends_on:
      - database              # Ensure the database starts before the web server

  database:
    build: ./data_base
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MySQL
      MYSQL_DATABASE: mydb                # Specify the name of the database to create
      MYSQL_USER: user                    # Set the username for MySQL
      MYSQL_PASSWORD: password            # Set the password for the MySQL user
    networks:
      - mon_reseau                        # Connect to the specified network
    volumes:
      - db_data:/var/lib/mysql           # Persist database data in a volume
    ports:
      - "3306:3306"                       # Expose MySQL port 3306 on the host for external access

networks:
  mon_reseau:
    driver: bridge                        # Use the bridge driver for the Docker network

volumes:
  db_data:                               # Define a volume for database data persistence
